config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :stories do
     resources:comments, only:[:create]
  end
  resources :stories do
    resources :comments, only: [:create]
  end
  
  resources :likes, only:[:create,:destory]

  get 'home/about'
  root 'home#index'
  get 'home/stories'

  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end
  
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <div>
  <%= link_to 'Medium Pro', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <button class="btn" type="submit"><%= link_to 'Your Stories', stories_path%></button>
  <button class="btn" type="submit">Membership</button>
  <button class="btn" type="submit">Write</button>
  <button class="btn " type="submit"><%= link_to 'Sign in', user_session_path%></button>
</div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
      </li>
    </ul>

    
    <form class="form-inline my-2 my-lg-0">
      <%#= <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> %>
      <%#= <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> %>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Hello</h1>
<%= button_to "logout", destroy_user_session_path, method: :delete %>
<%= link_to "Edit Profile", edit_user_registration_path %>

</br>
email: <%= current_user.email %> 
name : <%= current_user.name %>

app/views/home/request.html.erb
<div class="req-parent">

  <h2>Request</h2>

  <div class="underline"></div>

  <div class = "form">
  <% userdum = Userdum.new%>
  <%= form_with model: userdum do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, placeholder: "John Doe", required: true, class: "input" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "label" %>
      <%= f.email_field :email, placeholder: "someone@email.com", required: true, class: "input" %>
    </div>

    <div class="form-group">
      <%= f.label :contact, class: "label" %>
      <%= f.number_field :contact, placeholder: "+92xxx-xxxxxxx", required: true, class: "input" %>
    </div>


    <div class="form-group">
      <%= f.label :request, class: "label" %>
      <%= f.text_area :requestContent, rows: 6, placeholder: "Enter your request content", required: true, class: "input" %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit Request", class: "submit" %>
    </div>
  <% end %>
  </div>

</div>

app/views/home/subscription.html.erb
<div class="subs-parent">

<div class="columns">
  <ul class="price">
    <li class="header">Basic</li>
    <li class="grey">$ 9.99 / year</li>
    <li>10GB Storage</li>
    <li>10 Emails</li>
    <li>10 Domains</li>
    <li>1GB Bandwidth</li>
    <li class="grey"><%= link_to "Free", root_path, class: "btn" %></li>
  </ul>
</div>
<div class="columns">
  <ul class="price">
    <li class="header">Standard</li>
    <li class="grey">$ 14.99 / year</li>
    <li>15GB Storage</li>
    <li>40 Emails</li>
    <li>15 Domains</li>
    <li>5GB Bandwidth</li>
    <li class="grey"><script async
  src="https://js.stripe.com/v3/buy-button.js">
</script>

<stripe-buy-button
  buy-button-id="buy_btn_1NS024FaEE1q8n4Zeszm6Lmq"
  publishable-key="pk_test_51NRCMWFaEE1q8n4ZReSTbxP1Z8roAOa4SJCuSNeKpP8HSxhdaTaNfln91PtOQmdHv7dtA3qSfs3vWiusTsoEofa100jZopAcCu"
>
</stripe-buy-button></li>
  </ul>
</div>
<div class="columns">
  <ul class="price">
    <li class="header">Premium</li>
    <li class="grey">$ 19.99 / year</li>
    <li>30GB Storage</li>
    <li>100 Emails</li>
    <li>30 Domains</li>
    <li>10GB Bandwidth</li>
    <li class="grey"><script async
  src="https://js.stripe.com/v3/buy-button.js">
</script>

<stripe-buy-button
  buy-button-id="buy_btn_1NRzyGFaEE1q8n4ZKacFi9ae"
  publishable-key="pk_test_51NRCMWFaEE1q8n4ZReSTbxP1Z8roAOa4SJCuSNeKpP8HSxhdaTaNfln91PtOQmdHv7dtA3qSfs3vWiusTsoEofa100jZopAcCu"
>
</stripe-buy-button></li>
  </ul>
</div>

</div>