config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :stories do
     resources:comments, only:[:create]
  end
  resources :stories do
    resources :comments, only: [:create]
  end
  
  resources :likes, only:[:create,:destory]

  get 'home/about'
  root 'home#index'
  get 'home/stories'

  #devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/story.rb
class Story < ApplicationRecord
    belongs_to :user 
    has_many :likes
    has_many :comments
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[ show edit update destroy ]

  # GET /stories or /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1 or /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories or /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to story_url(@story), notice: "Story was successfully created." }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Story was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to story_url(@story), notice: "Story was successfully updated." }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def story_params
      params.require(:story).permit(:story_id, :title, :text)
    end

end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <% if story.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
        <% story.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

      <div>
        <%= form.label :Story %><br>
        <%= form.text_area :text, rows: 10, cols: 40 %>
    </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/stories/_story.html.erb
    <div id="<%= dom_id story %>">
  <p>
    <strong>Title:</strong>
    <%= story.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%=story.text %>
  </p>
 
    
  
</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Read this story", @story %> |
  <%= link_to "Back to stories", stories_path %>
</div>

app/views/stories/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Your Stories</h1>
<div class="row justify-content-center mt-4">
<div class="col-md-6" text-center>
<div id="stories">
  <% @stories.each do |story| %>
    <%= render story %>
    <p>
      <%= link_to "Read this story", story %>
    </p>
  <% end %>
</div>

<%= link_to " Write a new story", new_story_path %>
</div>.
</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render "form", story: @story %>

<br>

<div>
  <%= link_to "Back to your stories", stories_path %>
</div>

app/views/stories/show.html.erb
</br>
<div class="d-grid gap-2 d-md-flex justify-content-md-end "><button me-md-2 type="button" class="btn btn-outline-dark"><%= link_to "back to stories", stories_path %>
</button></div>
<div>
<p style="color: green"><%= notice %></p>

<%= render @story %>

<form action=" /likes" method="story">


<input type="hidden" name="like[story_id]" value="<%= @story.id %>">
<input type="submit" value="Like">
</form>

<button type="button" class="btn btn-outline-dark bm-4">
  <%= link_to "Edit this story", edit_story_path(@story) %> 
  </button>
  <%= button_to 'Delete this story',@story, method: :delete, class: 'btn btn-outline-danger mt-3'  %>

</div>